name: Publish Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git fetch --tags --force origin
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio-${{ hashFiles('platformio.ini') }}
          restore-keys: |
            ${{ runner.os }}-pio-
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Validate docs
        run: |
          npm install -g redoc-cli@0.13
          redoc-cli validate ./docs/openapi.yaml

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio intelhex

      - name: Build PlatformIO Project
        run: pio run

      - name: Prepare release
        run: |
          ./.prepare_release
          ./.prepare_docs

      - name: Upload production artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download production artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Create Release
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            console.log('environment', process.versions);

            const fs = require('fs').promises;

            const { repo: { owner, repo }, sha } = context;
            console.log({ owner, repo, sha });

            const tagName = process.env.GITHUB_REF_NAME;
            console.log('Creating release for tag:', tagName);

            const release = await github.rest.repos.createRelease({
              owner, repo,
              name: tagName,
              body: await fs.readFile('./dist/release-notes.txt', 'utf8'),
              tag_name: tagName,
              draft: false,
              make_latest: 'true',
              target_commitish: sha
            });

            console.log('created release', { release });

            for (let file of await fs.readdir('dist')) {
              if (file.endsWith('.bin')) {
                console.log('uploading', file);

                await github.rest.repos.uploadReleaseAsset({
                  owner, repo,
                  release_id: release.data.id,
                  name: file,
                  data: await fs.readFile(`./dist/${file}`)
                });
              }
            }

  publish_docs:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Download production artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Release docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/docs
